# remember to use echo -ne "" | base64 to get the correct value (without \n)
#
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  creationTimestamp: 
  labels:
    app: s3-backup-job
    io.shyrka.erebus/scope: test
    io.shyrka.erebus.tooling-info/role: config
  name: s3
data:
  # this is the Id of the S3 user
  s3-access-key-id: QUtJQUk1U01FMlVDV05URkJYNUE=
  # this is the Sccess key of the S3 user
  s3-secret-access-key: ZmxYNTF0R0t6K2t0Mytsc3gwcUNTdDBtT3FhWk51VVBJUCtSM2ZOQw==
  # this is the bucket where the back/restore will be placeS3 user
  s3-bucket: YmFja3VwLXJlc3RvcmUtYnVja2V0
  # this is the prefix aka subdirectory backup (good practice to have it as ${OPENSHIFT_NAMESPACE}/${DTBTYPE}_${DTBNAME}
  # oc config current-context | cut -d "/" -f 1
  s3-prefix: bXlzcWwvdGVzdGluZw==
  #This passphrase is used for gpg encryption
  gpg-passphrase: b29tKmVpLm45ZWVZNWVzaDZjaWUrWDNPaGI9YQ==

